name: Listar arquivos do reposit√≥rio

on:
  push:
    branches:
      - main

jobs:
  listar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Listar arquivos
        run: ls -l
